In [1]:
import numpy as np
import pandas as pd

def cubic_spline(x, y, a, b):
    n = len(x)
    h = np.diff(x)
    h = np.insert(h, 0, 0)
    

    # Проверка на ошибки
    if n < 2:
        return None, 1  # Недостаточно точек
    if not np.all(np.diff(x) > 0):
        return None, 2  # Нарушен порядок возрастания


    matrix = np.zeros((n,n))  # 3 диагональная матрица
    F = np.zeros(n)           # вектор правых частей
    
    # условия на с_0 = А
    matrix[0][0] = 1
    F[0] = a

    #заполнение 3 диагоналей
    #заполнение главной диагонали
    for i in range(1, n - 1):
        matrix[i][i] = 2 * (h[i] + h[i+1]) #h[i+1] + h[i]
    #заполнение диагонали над главной
    for i in range(1, n - 1):
        matrix[i][i+1] = h[i+1]
    #заполнение диагонали под главной
    for i in range(0, n - 2):
        matrix[i+1][i] = h[i+1]
    #условия на B
    matrix[n-1][n-2] = 1/2
    matrix[n-1][n-1] = 1

    #заполнить F
    """
    обращаемся к h[(n-1)] так какдобавили в начало 0
    """
    
    F[0] = a
    F[n-1] = (3/h[(n-1)]) * (b - ((y[n-1] - y[n-2])/h[(n-1)])) 

    for i in range(1, n-1):
        F[i+1] = 6 * (y[i+1]-y[i])/h[i+2] - (y[i]-y[i-1])/h[i+1] )   #переделать неправильно
    
    print(F)

# x = np.array([1, 2, 3, 4])
# y = np.array([1, 4, 9, 16])
# a, b = 2, 2


x = np.array([0, 2, 4, 5])
y = np.array([0, 4, 16, 25])
a, b = 2, 10 


cubic_spline(x, y, a, b)

In [254]:
# или так (исправлен момент с h)

import numpy as np

def solve_system(matr, vec, n):
    # n — это размер системы (количество узлов)

    # Массивы для решения методом прогонки
    res = np.zeros(n)
    mu = np.zeros(n)
    nu = np.zeros(n)

    # Прямой ход прогонки (прямой проход)
    # Учитываем, что matr[:, 0] - поддиагональ, matr[:, 1] - главная диагональ, matr[:, 2] - наддиагональ
    mu[0] = vec[0] / matr[0][0]  # делим на первый элемент главной диагонали
    nu[0] = -matr[0][1] / matr[0][0]  # - matr[0][2] (если бы было три диагонали)

    # Проходим по всем элементам от 1 до n-1
    for i in range(1, n - 1):
        denominator = matr[i][i] + matr[i][i - 1] * nu[i - 1]
        mu[i] = (vec[i] - matr[i][i - 1] * mu[i - 1]) / denominator
        nu[i] = -matr[i][i + 1] / denominator

    # Последний шаг прогонки
    mu[n - 1] = (vec[n - 1] - matr[n - 1][n - 2] * mu[n - 2]) / (matr[n - 1][n - 1] + matr[n - 1][n - 2] * nu[n - 2])

    # Обратный ход (обратный проход)
    res[n - 1] = mu[n - 1]
    for i in range(n - 2, -1, -1):
        res[i] = mu[i] + nu[i] * res[i + 1]

    return res


def cubic_spline(x, y, a, b):
    n = len(x)
    h = np.diff(x)  # Оставляем h без вставки нуля, это длины отрезков между узлами

    # Проверка на ошибки
    if n < 2:
        return None, None, 1  # Недостаточно точек
    if not np.all(np.diff(x) > 0):
        return None, None, 2  # Нарушен порядок возрастания

    matrix = np.zeros((n, n))  # Трехдиагональная матрица
    F = np.zeros(n)            # Вектор правых частей

    # Условие на c_0 = A
    matrix[0][0] = 1
    F[0] = a

    # Заполнение главной диагонали
    for i in range(1, n - 1):
        matrix[i][i] = 2 * (h[i - 1] + h[i])  # Индексация скорректирована для h

    # Заполнение над главной диагональю
    for i in range(1, n - 1):
        matrix[i][i + 1] = h[i]  # Над главной диагональю идет h[i]

    # Заполнение под главной диагональю
    for i in range(1, n - 1):
        matrix[i][i - 1] = h[i - 1]  # Под главной диагональю идет h[i-1]

    # Условие на B
    matrix[n - 1][n - 2] = 1 / 2
    matrix[n - 1][n - 1] = 1

    # Заполнение вектора правых частей F
    F[n - 1] = (3 / h[n - 2]) * (b - (y[n - 1] - y[n - 2]) / h[n - 2])

    for i in range(1, n - 1):
        F[i] = 6 * ((y[i + 1] - y[i]) / h[i] - (y[i] - y[i - 1]) / h[i - 1])

    # print("Матрица:")
    # print(matrix)
    # print("Вектор F:")
    # print(F)

    return matrix, F, 0



In [265]:
# Чтение данных из файла
def read_input(filename):
    with open(filename, 'r') as f:
        lines = f.readlines()
    
    x = np.array([float(val) for val in lines[0].split()])
    y = np.array([float(val) for val in lines[1].split()])
    a = float(lines[2].strip())  # Вторая производная в начале
    b = float(lines[3].strip())  # Первая производная в конце
    
    return x, y, a, b

# Запись данных в файл
def write_output(filename, x, y, second_derivatives):
    df = pd.DataFrame({
        'x': x,
        'f(x)': y,
        "f''(x)": second_derivatives,
    })
    df.to_csv(filename, index=False)

# Главная функция, связывающая ввод и вывод
def main(input_file, output_file):
    x, y, a, b = read_input(input_file)

    matr, F, IER = cubic_spline(x, y, a, b)

    if IER == 0:
        second_derivatives = solve_system(matr, F, len(x))
        write_output(output_file, x, y, second_derivatives)
        print(f"Результаты записаны в файл: {output_file}")
    else:
        print(f"Ошибка при построении сплайна. Код ошибки: {IER}")

# Запуск программы с файлами
input_file = 'test_cubic.txt'
output_file = 'output.csv'
main(input_file, output_file)

Результаты записаны в файл: output.csv


---
---
---

In [267]:
# Пример использования
x = np.array([0, 2, 4, 5])
y = np.array([0, 4, 16, 25])
a, b = 2, 10 


# Пример матрицы и вектора правых частей
matr, F, IER = cubic_spline(x, y, a, b)

# Решаем систему методом прогонки
C = solve_system(matr, F, len(x))

print("Решение системы (вторые производные):")
print(C)

# Вывод таблицы
if IER == 0:
    table = pd.DataFrame({
        'x': x,  
        'f(x)': y,  
        "f''(x)": C,  
    })
    print(table.to_string(index=False))
else:
    print("Ошибка:", IER)


Решение системы (вторые производные):
[2. 2. 2. 2.]
 x  f(x)  f''(x)
 0     0     2.0
 2     4     2.0
 4    16     2.0
 5    25     2.0


In [269]:
# Тест 2: Линейная функция f(x) = 2x + 1
x = np.array([0, 1, 2, 3, 4])
y = np.array([1, 3, 5, 7, 9])
a = 0  # Вторая производная в начале
b = 2  # Первая производная в конце

# Пример матрицы и вектора правых частей
matr, F, IER = cubic_spline(x, y, a, b)

# Решаем систему методом прогонки
C = solve_system(matr, F, len(x))

print("Решение системы (вторые производные) для линейной функции:")
print(C)

# Вывод таблицы
if IER == 0:
    table = pd.DataFrame({
        'x': x,  
        'f(x)': y,  
        "f''(x)": C,  
    })
    print("Линейная функция f(x) = 2x + 1")
    print(table.to_string(index=False))
else:
    print("Ошибка:", IER)


Решение системы (вторые производные) для линейной функции:
[0. 0. 0. 0. 0.]
Линейная функция f(x) = 2x + 1
 x  f(x)  f''(x)
 0     1     0.0
 1     3     0.0
 2     5     0.0
 3     7     0.0
 4     9     0.0


In [271]:
# Тест 1: Константная функция f(x) = 4
x = np.array([0, 1, 2, 3, 4])
y = np.array([4, 4, 4, 4, 4])
a = 0  # Вторая производная в начале
b = 0  # Первая производная в конце

# Пример матрицы и вектора правых частей
matr, F, IER = cubic_spline(x, y, a, b)

# Решаем систему методом прогонки
C = solve_system(matr, F, len(x))

print("Решение системы (вторые производные) для константной функции:")
print(C)

# Вывод таблицы
if IER == 0:
    table = pd.DataFrame({
        'x': x,  
        'f(x)': y,  
        "f''(x)": C,  
    })
    print("Константная функция f(x) = 4")
    print(table.to_string(index=False))
else:
    print("Ошибка:", IER)


Решение системы (вторые производные) для константной функции:
[0. 0. 0. 0. 0.]
Константная функция f(x) = 4
 x  f(x)  f''(x)
 0     4     0.0
 1     4     0.0
 2     4     0.0
 3     4     0.0
 4     4     0.0


In [273]:
# Тест 4: Кубическая функция f(x) = x^3 - 3x^2 + 2x
x = np.array([0, 1, 2, 3, 4])
y = x**3 - 3 * x**2 + 2 * x  # Кубическая функция
a = -6  # Вторая производная в начале
b = 26  # Первая производная в конце

# Пример матрицы и вектора правых частей
matr, F, IER = cubic_spline(x, y, a, b)

# Решаем систему методом прогонки
C = solve_system(matr, F, len(x))

print("Решение системы (вторые производные) для кубической функции:")
print(C)

# Вывод таблицы
if IER == 0:
    table = pd.DataFrame({
        'x': x,  
        'f(x)': y,  
        "f''(x)": C,  
    })
    print("Кубическая функция f(x) = x^3 - 3x^2 + 2x")
    print(table.to_string(index=False))
else:
    print("Ошибка:", IER)


Решение системы (вторые производные) для кубической функции:
[-6.  0.  6. 12. 18.]
Кубическая функция f(x) = x^3 - 3x^2 + 2x
 x  f(x)  f''(x)
 0     0    -6.0
 1     0     0.0
 2     0     6.0
 3     6    12.0
 4    24    18.0
